<?php
if (isset($user->username)) {
    $last = (null !== $user->last_ip) ?
        date('D M j, Y g:i A', strtotime($user->last_login)) . ' (' . (('' !== $user->last_ip) ? $user->last_ip : 'N/A') . ')' :
        '(N/A)';
    echo '    <p>' . PHP_EOL;
    echo '        <strong>Logged in as:</strong> <a href="' . BASE_PATH . '/member/profile">' . $user->username . '</a> | <a href="' . BASE_PATH . '/member/logout">Logout</a><br />' . PHP_EOL;
    echo '        <span style="font-size: 0.9em;"><strong>Last Login:</strong> ' . $last . '</span>' . PHP_EOL;
    echo '    </p>' . PHP_EOL;
?>
    <ul>
        <li><a href="<?php echo BASE_PATH; ?>/member">Home</a></li>
<?php
if (($globalAccess) || ($acl->isAllowed($role, 'profile', 'edit')))
    echo '        <li><a href="' . BASE_PATH . '/member/profile">Profile</a></li>';
?>
        <li><a href="<?php echo BASE_PATH; ?>/member/unsubscribe">Unsubscribe</a></li>
    </ul>
<?php
}
?>
