<?php include __DIR__ . '/../header.phtml'; ?>
    <h1 style="color: #00f;">Phire Module &gt; <?php echo $title; ?></h1>
<?php
include __DIR__ . '/../nav.phtml';

echo '    <p><a href="' . BASE_PATH . APP_URI . '/roles/add">[+] Add</a></p>' . PHP_EOL;
if (isset($form)) {
    echo $form;
} else if (isset($roles[0])) {
    $i = null;
    echo '    <form action="' . BASE_PATH . APP_URI . '/roles/remove" method="post">' . PHP_EOL;
    echo '        <table cellpadding="5" cellspacing="5" border="0">' . PHP_EOL;
    echo '           <tr><th>ID #</th><th>Type</th><th>Name</th><th>Remove?</th></tr>' . PHP_EOL;
    foreach ($roles as $role) {
        if ($role->id != 3001) {
            $remove = '<input type="checkbox" name="remove_roles[]" id="remove_roles' . $i . '" value="' . $role->id . '" />';
            $i++;
        } else {
            $remove = null;
        }
        echo '           <tr><td>' . $role->id . '</td><td>' . $role->type . '</td><td><a href="' . BASE_PATH . APP_URI . '/roles/edit/' . $role->id . '">' . $role->name . '</a></td><td>' . $remove . '</td></tr>' . PHP_EOL;
    }
    echo '           <tr><td colspan="4"><input type="submit" name="submit" value="Remove" /></td></tr>' . PHP_EOL;
    echo '        </table>' . PHP_EOL;
    echo '    </form>' . PHP_EOL;
} else {
    echo '    <p>There are currently no roles.</p>' . PHP_EOL;
}

include __DIR__ . '/../footer.phtml';
?>