<?php echo '<?xml version="1.0" encoding="utf-8"?>' . PHP_EOL; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<head>
    <title>Phire CMS 2.0.0 &gt; System</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
        .required {
            font-weight: bold;
            color: #098df2;
        }
        .error {
            font-weight: bold;
            color: #f00;
        }
        dt {
            margin: 0;
            padding: 10px 5px 10px 5px;
            float: left;
            clear: left;
            width: 250px;
            text-align: right;
        }
        dd {
            margin: 0;
            padding: 10px 5px 10px 5px;
            float: left;
        }
    </style>
    <script type="text/javascript" src="http://www.jaxjs.org/latest/jax.min.js"></script>
    <script type="text/javascript">
        var checkConfig = function(url) {
            if (url != location.href) {
                if (JaxXmlHttp().getRequest(url) == "The config file is not properly configured. Please check the config file or install the system.") {
                    alert('Please copy and paste the code into the \'config.php\' file.');
                    return false;
                } else {
                    return true;
                }
            }
        }
    </script>
</head>
<body>
