<?php echo '<?xml version="1.0" encoding="utf-8"?>' . PHP_EOL; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<head>
    <title>Phire CMS 2.0.0 &gt; System</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
        .required {
            font-weight: bold;
            color: #098df2;
        }
        .error {
            font-weight: bold;
            color: #f00;
        }
        dt {
            margin: 0;
            padding: 10px 5px 10px 5px;
            float: left;
            clear: left;
            width: 250px;
            text-align: right;
        }
        dd {
            margin: 0;
            padding: 10px 5px 10px 5px;
            float: left;
        }
    </style>
</head>
<body>
