<?php include __DIR__ . '/../header.phtml'; ?>
    <h1 style="color: #00f;">Phire Module &gt; <?php echo $title; ?></h1>
    <p>
        The configuration file is not writable and the configuration has not been written to the file.<br />
        You will have to copy the code below and paste it into the 'config.php' file to continue.
    </p>
<textarea id="config" rows="25" cols="120" onfocus="this.select();">
<?php echo $config; ?>
</textarea>
    <p><a href="<?php echo $_SERVER['REQUEST_URI']; ?>">Continue</a></p>
<?php include __DIR__ . '/../footer.phtml'; ?>