<?php include __DIR__ . '/header.phtml'; ?>
    <div id="sub-header"></div>
<!-- Content //-->
    <div id="content">
        <div id="content-area">
            <h1>Category <?php echo $separator . ' ' . $title; ?></h1>
<?php if (count($items) > 0): ?>
<?php foreach ($items as $item): ?>
            <div class="list-div"><a href="<?php echo $base_path . '/category' . $item->category_uri . '">' . $item->category_title . '</a> ' . $separator . ' <a href="' . $base_path . $item->uri . '">' . $item->title; ?></a></div>
<?php endforeach; ?>
<?php else: ?>
            <p>No items found in this category.</p>
<?php endif; ?>
        </div>
<?php include __DIR__ . '/sidebar.phtml'; ?>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>