<?php include __DIR__ . '/header.phtml'; ?>
    <div id="sub-header"></div>
<!-- Content //-->
    <div id="content">
        <div id="content-area">
            <h1><?php echo $title; ?></h1>
<?php if (count($results) > 0): ?>
<?php foreach ($results as $result): ?>
            <div class="list-div">
                <span class="date"><?php echo date($datetime_format, strtotime($result->published)); ?></span>
                <a href="<?php echo $base_path . '/' . $date . $result->uri . '">' . $result->title; ?></a>
                <p><?php echo strip_tags(substr($result->content, 0, 200)) . '...'; ?></p>
            </div>
<?php endforeach; ?>
<?php else: ?>
            <p>No date results found.</p>
<?php endif; ?>
        </div>
<?php include __DIR__ . '/sidebar.phtml'; ?>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>