<?php include __DIR__ . '/header.phtml'; ?>
    <div id="sub-header"></div>
<!-- Content //-->
    <div id="content">
        <div id="content-area">
            <h1><?php echo $title; ?></h1>
<?php if (count($items) > 0): ?>
<?php if (isset($page_links) && (null !== $page_links)): ?>
            <div class="page-links"><?php echo $page_links; ?></div>
<?php endif; ?>
<?php foreach ($items as $item): ?>
            <div class="list-div">
                <span class="date"><?php echo date($datetime_format, strtotime($item->published)); ?></span>
                <a href="<?php echo $base_path . (($item->uri != '/') ? '/' . $date : '') . $item->uri . '">' . $item->title; ?></a>
                <p><?php echo strip_tags(substr($item->content, 0, 200)) . '...'; ?></p>
            </div>
<?php endforeach; ?>
<?php if (isset($page_links) && (null !== $page_links)): ?>
            <div class="page-links"><?php echo $page_links; ?></div>
<?php endif; ?>
<?php else: ?>
            <p>No date results found.</p>
<?php endif; ?>
        </div>
<?php include __DIR__ . '/sidebar.phtml'; ?>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>