<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        <?php echo $site_title . ' ' . $separator . ' ' . (!empty($breadcrumb_title) ? $breadcrumb_title : $title). PHP_EOL; ?>
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="author" content="Phire CMS 2" />
    <meta name="keywords" content="<?php echo (isset($keywords) ? $keywords : null); ?>" />
    <meta name="description" content="<?php echo (isset($description) ? $description : null); ?>" />
    <meta name="robots" content="all" />

    <link rel="stylesheet" type="text/css" href="<?php echo $base_path . $content_path; ?>/extensions/themes/default/css/styles.css" />
    <link rel="shortcut icon" href="<?php echo $base_path . $content_path; ?>/extensions/themes/default/img/phire.ico" type="image/ico" />

</head>

<body>
<div id="container">
    <div id="top-header">
        <form id="search-form" action="<?php echo $base_path; ?>/search" method="get">
            <div><input type="text" name="title" size="20" value="" /></div>
            <div><input type="submit" name="submit" value="SEARCH" /></div>
        </form>
        <h1><a href="<?php echo ($base_path != '') ? $base_path : '/'; ?>">My Default Site</a></h1>
    </div>
    <div id="nav-bar">
<?php echo (isset($main_nav) ? $main_nav : null); ?>
    </div>

