        <div id="sidebar">
            <h2>Sidebar</h2>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin volutpat. Maecenas laoreet tempus quam. Maecenas faucibus semper leo.</p>
<?php if (isset($category_nav)): ?>
            <h4>Categories</h4>
<?php echo $category_nav; ?>
<?php endif; ?>
            <h4>Archives</h4>
            <ul>
<?php for ($y = date('Y'); $y > (date('Y') - 3); $y--): ?>
<?php
$archive = $phire->getContentByDate($y . '-12-31 23:59:59', $y . '-01-01 00:00:00', 0);
if (count($archive) > 0): ?>
                <li><a href="<?php echo $base_path . '/' . $y; ?>"><?php echo $y . ' (' . count($archive) . ')'; ?></a></li>
<?php endif; ?>
<?php endfor; ?>
            </ul>
        </div>
