<?php include __DIR__ . '/header.phtml'; ?>
    <div id="sub-header"></div>
<!-- Content //-->
    <div id="content">
        <div id="content-area">
            <h1><?php echo $title; ?></h1>
<?php if (isset($breadcrumb)): ?>
            <div id="breadcrumb"><?php echo $separator . ' ' . $breadcrumb; ?></div>
<?php endif; ?>
<?php echo (isset($content) ? $content : null); ?>
        </div>
<?php include __DIR__ . '/sidebar.phtml'; ?>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>