<!DOCTYPE html>
<!-- Header //-->
<html>

<head>
    <title>Phire Module &gt; <?php echo $title; ?></title>
    <style type="text/css">
        html {
            margin: 0;
            padding: 0;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 0.75em;
        }
        a {
            font-weight: bold;
        }
        p {
            margin: 0 0 10px 0;
            padding: 0;
            line-height: 1.4em;
        }
        dt {
            clear: left;
            float: left;
            margin: 0;
            padding: 3px;
            width: 200px;
            text-align: right;
        }
        dd {
            float: left;
            margin: 0;
            padding: 3px;
        }
        fieldset {
            margin: 0;
            padding: 0 3px 6px 3px;
            border: none;
        }
        .required { color: #0090ff; font-weight: bold; }
        .error { color: #f00; font-weight: bold; }
    </style>
</head>
<body>
