<?php include __DIR__ . '/header.phtml'; ?>
    <h1 style="color: #00f;">Phire Module &gt; <?php echo $title; ?></h1>
<?php
if (isset($error))
    echo '    <h4 style="color: #f00;">' . $error . '</h4>' . PHP_EOL;
echo $form;

echo '    <p style="clear: left;">' .
    (($register) ?'<a href="' . BASE_PATH . APP_URI . '/register">Register</a> | ' : null) .
    '<a href="' . BASE_PATH . APP_URI . '/forgot">Forgot</a>' .
    (($unsubscribe) ? ' | <a href="' . BASE_PATH . APP_URI . '/unsubscribe">Unsubscribe</a>' : null). '</p>' . PHP_EOL;

include __DIR__ . '/footer.phtml';
?>