<?php
if (isset($user->username)) {
    $last = (null !== $user->last_ip) ?
        date('D M j, Y g:i A', strtotime($user->last_login)) . ' (' . (('' !== $user->last_ip) ? $user->last_ip : 'N/A') . ')' :
        '(N/A)';
    echo '    <p>' . PHP_EOL;
    echo '        <strong>Logged in as:</strong> <a href="' . BASE_PATH . APP_URI . '/profile">' . $user->username . '</a> | <a href="' . BASE_PATH . APP_URI . '/unsubscribe">Unsubscribe</a> | <a href="' . BASE_PATH . APP_URI . '/logout">Logout</a><br />' . PHP_EOL;
    echo '        <span style="font-size: 0.9em;"><strong>Last Login:</strong> ' . $last . '</span>' . PHP_EOL;
    echo '    </p>' . PHP_EOL;
}
?>
    <ul>
        <li><a href="<?php echo BASE_PATH . APP_URI; ?>">Home</a></li>
        <li>
            <a href="<?php echo BASE_PATH . APP_URI; ?>/content">Content</a>
            <ul>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/content/pages">Pages</a></li>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/content/templates">Templates</a></li>
            </ul>
        </li>
        <li>
            <a href="<?php echo BASE_PATH . APP_URI; ?>/media">Media</a>
            <ul>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/media/files">Files</a></li>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/media/images">Images</a></li>
            </ul>
        </li>
        <li>
            <a href="<?php echo BASE_PATH . APP_URI; ?>/extensions">Extensions</a>
            <ul>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/extensions/themes">Themes</a></li>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/extensions/plugins">Plugins</a></li>
            </ul>
        </li>
        <li>
            <a href="<?php echo BASE_PATH . APP_URI; ?>/system">System</a>
            <ul>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/system/sites">Sites</a></li>
                <li>
                    <a href="<?php echo BASE_PATH . APP_URI; ?>/system/users">Users</a>
                    <ul>
                        <li><a href="<?php echo BASE_PATH . APP_URI; ?>/system/sessions">Sessions</a></li>
                        <li><a href="<?php echo BASE_PATH . APP_URI; ?>/system/roles">Roles</a></li>
                        <li><a href="<?php echo BASE_PATH . APP_URI; ?>/system/types">Types</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo BASE_PATH . APP_URI; ?>/system/config">Configuration</a></li>
            </ul>
        </li>
    </ul>
