<?php include __DIR__ . '/../header.phtml'; ?>
    <h1 style="color: #00f;">Phire Module &gt; <?php echo $title; ?></h1>
<?php
include __DIR__ . '/../nav.phtml';

echo '    <p><a href="' . BASE_PATH . APP_URI . '/users/add">[+] Add</a></p>' . PHP_EOL;
if (isset($form)) {
    if (isset($error))
        echo '    <h4 style="color: #f00;">' . $error . '</h4>' . PHP_EOL;
    echo $form;
} else if (isset($users[0])) {
    $i = null;
    echo '    <form action="' . BASE_PATH . APP_URI . '/users/remove" method="post">' . PHP_EOL;
    echo '        <table cellpadding="5" cellspacing="5" border="0">' . PHP_EOL;
    echo '           <tr><th>ID #</th><th>Type</th><th>Role</th><th>Username</th><th>Name</th><th>Email</th><th>Remove?</th></tr>' . PHP_EOL;
    foreach ($users as $usr) {
        if (($usr->id != $user->id) && ($acl->isAllowed($role, 'users', 'remove'))) {
            $remove = '<input type="checkbox" name="remove_users[]" id="remove_users' . $i . '" value="' . $usr->id . '" />';
            $i++;
        } else {
            $remove = null;
        }
        echo '           <tr><td>' . $usr->id . '</td><td><a href="' . BASE_PATH . APP_URI . '/users/type/' . $usr->id . '">' . $usr->type . '</a></td><td>' . ((null !== $usr->name) ? $usr->name : '(Blocked)') . '</td><td><a href="' . BASE_PATH . APP_URI . '/users/edit/' . $usr->id . '">' . $usr->username . '</a></td><td>' . $usr->first_name . ' ' . $usr->last_name . '</td><td>' . $usr->email . '</td><td>' . $remove . '</td></tr>' . PHP_EOL;
    }
    echo '           <tr><td colspan="3"><input type="submit" name="submit" value="Remove" /></td></tr>' . PHP_EOL;
    echo '        </table>' . PHP_EOL;
    echo '    </form>' . PHP_EOL;
} else {
    echo '    <p>There are currently no users.</p>' . PHP_EOL;
}

include __DIR__ . '/../footer.phtml';
?>