<?php include __DIR__ . '/../header.phtml'; ?>
    <h1 style="color: #00f;">Phire Module &gt; <?php echo $title; ?></h1>
<?php
include __DIR__ . '/../nav.phtml';

if (isset($sessions[0])) {
    $i = null;
    echo '    <form action="' . BASE_PATH . APP_URI . '/users/sessions/remove" method="post">' . PHP_EOL;
    echo '        <table cellpadding="5" cellspacing="5" border="0">' . PHP_EOL;
    echo '           <tr><th>ID #</th><th>Type</th><th>Username</th><th>IP</th><th>User Agent</th><th>Start</th><th>Remove?</th></tr>' . PHP_EOL;
    foreach ($sessions as $session) {
        if ($session->id != $user->sess_id) {
            $remove = '<input type="checkbox" name="remove_sessions[]" id="remove_sessions' . $i . '" value="' . $session->id . '" />';
            $i++;
        } else {
            $remove = null;
        }
        echo '           <tr><td>' . $session->id . '</td><td>' . $session->type . '</td><td><a href="' . BASE_PATH . APP_URI . '/users/edit/' . $session->user_id . '">' . $session->username . '</a></td><td>' . $session->ip . '</td><td>' . $session->ua . '</td><td>' . date('D M j, Y g:i A', strtotime($session->start)) . '</td><td>' . $remove . '</td></tr>' . PHP_EOL;
    }
    echo '           <tr><td colspan="7"><input type="submit" name="submit" value="Remove" /></td></tr>' . PHP_EOL;
    echo '        </table>' . PHP_EOL;
    echo '    </form>' . PHP_EOL;
} else {
    echo '    <p>There are currently no sessions.</p>' . PHP_EOL;
}

include __DIR__ . '/../footer.phtml';
?>